spec:
  structures:
    - content_blocks
  label: List
  description: Displays items in a list with icons as markers
  icon: list
  tags:

blueprint:
  items:
  item_gap: sm
  direction: vertical
  alignment: start
  size: md
  icon_gap: sm
  icon_background: none

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  items:
    type: array
    options:
      structures: _structures.item
  item_gap:
    type: select
    comment: Contol the gap between list items
    options:
      values:
        - name: Extra Small
          value: xs
        - name: Small
          value: sm
        - name: Medium
          value: md
        - name: Large
          value: lg
        - name: Extra Large
          value: xl
        - name: 2xl
          value: 2xl
      value_key: value
      preview:
        text:
          - key: name
  direction:
    type: select
    options:
      values:
        - value: horizontal
          name: Horizontal
        - value: vertical
          name: Vertical
      value_key: value
      preview:
        text:
          - key: name
  alignment:
    type: select
    options:
      values:
        - value: start
          name: Start
        - value: center
          name: Center
        - value: end
          name: End
      value_key: value
      preview:
        text:
          - key: name
  size:
    comment: Controls the size of the icon and text
    type: select
    options:
      values:
        - value: sm
          name: Small
        - value: md
          name: Medium
        - value: lg
          name: Large
      value_key: value
      preview:
        text:
          - key: name
  icon_background:
    type: select
    options:
      values:
        - value: none
          name: None
        - value: subtle
          name: Subtle
      value_key: value
      preview:
        text:
          - key: name
    comment: The background style for the icon
  icon_gap:
    comment: Control the gap between the icon and the text
    type: select
    options:
      values:
        - name: Extra Small
          value: xs
        - name: Small
          value: sm
        - name: Medium
          value: md
        - name: Large
          value: lg
        - name: Extra Large
          value: xl
        - name: 2xl
          value: 2xl
      value_key: value
      preview:
        text:
          - key: name

_structures:
  item:
    values:
      - label: List item
        icon: text_fields
        value:
          text: ""
          icon:
        _inputs:
          text:
            type: markdown
            options:
              bold: true
              italic: true
              link: true
              strike: true
              subscript: true
              superscript: true
              underline: true
              undo: true
              redo: true
              removeformat: true
              copyformatting: true
          icon:
            type: select
            options:
              values: _select_data.icons
            comment: The name of the icon to display from the icon library
