spec:
  structures:
    - content_blocks
  label: Icon
  description: Displays an icon from your icon library.
  icon: star
  tags: []

blueprint:
  name:
  size: lg
  background: none

preview:

_inputs:
  name:
    type: select
    options:
      values: _select_data.icons
  size:
    type: select
    options:
      values:
        - none
        - sm
        - md
        - lg
  background:
    type: select
    options:
      values:
        - none
        - subtle
