spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Definition List
  description: "Useful for displaying key-value pairs, ideal for glossaries, opening times, etc."
  icon: dns
  tags: []

blueprint:
  items:
  horizontalAlignment: start

preview:

_inputs:
  items:
    type: array
    options:
      structures: _structures.item
  horizontalAlignment:
    type: select
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End

_structures:
  item:
    values:
      - label: Definition List Item
        icon: list
        value:
          _component: definition-list-item
          title:
          text:
        _inputs:
          title:
            type: text
            comment: A bolded title for the list item.
          text:
            type: textarea
            comment: The text content of the list item.
